// import "./globals.css";
import { Inter } from "next/font/google";
import "../styles/index.scss";
import "../styles/custom.scss";
import FrontHeader from "../components/FrontHeader";
import FrontFooter from "../components/FrontFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body suppressHydrationWarning className="front">
        <FrontHeader />
        <main className="front-main">{children}</main>
        <FrontFooter />
      </body>
    </html>
  );
}
